Your task is to resolve an "element not found" exception from Selenium by providing a working locator.
You will be successful when the test runs successfully with this locator.
The selenium exception message is "{seleniumExceptionMessage}".
To find the locator, you will examine the HTML body {htmlBody}, the Selenium page object's code {pageSourceCode} was called in method {callMethodPage}.
The Cucumber step code {stepsSourceCode} that calls the Selenium page object from method {callStepMethod} gives more inside to understand the test context.
Provide a locator that is unique and stable in the attribute "locator".
Update the page source code with the changed locator for merging in the attribute "pageSourceCode".
Provide a concise explanation of the changes made to the source code and the locator in the attribute "explanation".

{format}