spring:
  datasource:
      url: jdbc:h2:~/taxishare;AUTO_SERVER=TRUE
      driverClassName: org.h2.Driver
      username: user
      password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub